# Generated by Django 5.2.13 on 2026-05-10 08:51

import bakery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_alter_product_options_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cookies', '🍪 Cookies'), ('lattes', '☕ Lattes'), ('waffles', '🧇 Waffles'), ('cakes', '🎂 Cakes'), ('drinks', '🥤 Drinks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bakery.models.get_product_image_path),
        ),
    ]
