# Generated by Django 5.2.13 on 2026-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_remove_product_image_url_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cookies', '🍪 Cookies'), ('lattes', '☕ Lattes'), ('waffles', '🧇 Waffles'), ('cakes', '🎂 Cakes'), ('drinks', '🥤 Drinks'), ('pastries', '🥐 Pastries'), ('breads', '🍞 Breads')], max_length=20),
        ),
    ]
